const translations = {
  de: {
  "nav.home": "Start",
  "nav.listings": "Angebote",
  "nav.faq": "FAQ",
  "nav.contact": "Kontakt",
  "nav.impress": "Impressum",
  "nav.agb": "AGB",
  "nav.privacy": "Datenschutz",
  "agb.title": "Allgemeine Geschäftsbedingungen (AGB)",
  "agb.scope": "1. Geltungsbereich",
  "agb.scope.text": "Diese AGB gelten für alle Nutzer der Online-Plattform Residare (nachfolgend „Residare“ genannt), betrieben durch den Einzelunternehmer Paul Smith. Sie regeln das Verhältnis zwischen dem Betreiber und den Besuchern sowie registrierten Nutzern der Plattform.",
  "agb.services": "2. Leistungen",
  "agb.services.text": "Residare bietet die Möglichkeit, Immobilienanzeigen einzusehen und eigene Angebote zu veröffentlichen. Der Betreiber agiert nicht als Makler und vermittelt keine Verträge. Alle Leistungen erfolgen im Rahmen der gesetzlichen Möglichkeiten ohne Maklerlizenz.",
  "agb.costs": "3. Kostenpflichtige Dienste",
  "agb.costs.text": "Residare behält sich vor, bestimmte Funktionen – wie das Erstellen oder Hervorheben von Inseraten – künftig kostenpflichtig anzubieten. Die Nutzer werden vorab deutlich informiert.",
  "agb.withdrawal": "4. Widerrufsrecht",
  "agb.withdrawal.text": "Verbraucher haben das Recht, innerhalb von 14 Tagen nach Vertragsabschluss ohne Angabe von Gründen zu widerrufen. Die Details und ein Musterformular sind unter „Widerrufsbelehrung“ zu finden.",
  "agb.liability": "5. Haftung",
  "agb.liability.text": "Residare übernimmt keine Gewähr für die Richtigkeit, Vollständigkeit oder Aktualität der veröffentlichten Inhalte. Für externe Links ist ausschließlich der jeweilige Betreiber verantwortlich.",
  "agb.law": "6. Anwendbares Recht",
  "agb.law.text": "Es gilt ausschließlich deutsches Recht. Gerichtsstand ist der Sitz des Betreibers.",
  "agb.language": "7. Sprache",
  "agb.language.text": "Diese AGB sind in deutscher und polnischer Sprache abrufbar. Im Zweifelsfall ist ausschließlich die deutsche Fassung maßgeblich.",
  "privacy.title": "Datenschutzerklärung",
  "privacy.controller": "1. Verantwortlicher",
  "privacy.controller.text": "Paul Smith – Residare (Einzelunternehmen)\\nAdresse folgt\\nE-Mail: info@residare.de",
  "privacy.hosting": "2. Hosting",
  "privacy.hosting.text": "Unsere Website wird bei einem europäischen Hosting-Anbieter betrieben. Die dort gespeicherten Daten (z. B. IP-Adressen, Zugriffszeitpunkte) dienen dem sicheren und stabilen Betrieb und werden automatisch in Logfiles protokolliert.",
  "privacy.accessData": "3. Zugriffsdaten und Server-Logs",
  "privacy.accessData.text": "Beim Besuch unserer Website erheben wir automatisiert Daten über Zugriffe und speichern diese als Server-Logfiles. Dazu zählen: besuchte Seiten, Uhrzeit, Browsertyp, Betriebssystem, Referrer-URL, IP-Adresse. Diese Daten dienen ausschließlich der Sicherstellung eines störungsfreien Betriebs.",
  "privacy.cookies": "4. Cookies",
  "privacy.cookies.text": "Wir verwenden Cookies, um grundlegende Funktionen zu ermöglichen und die Nutzung zu analysieren. Technisch notwendige Cookies sind für den Betrieb der Seite unverzichtbar. Optional können Tracking-Cookies eingesetzt werden, sofern du einwilligst.",
  "privacy.contactform": "5. Kontaktformular",
  "privacy.contactform.text": "Wenn du über unser Formular Kontakt aufnimmst, speichern wir deine Angaben zur Bearbeitung der Anfrage sowie für Rückfragen. Diese Daten geben wir nicht ohne Einwilligung weiter.",
  "privacy.googlefonts": "6. Google Fonts",
  "privacy.googlefonts.text": "Auf unserer Website werden Google Fonts lokal eingebunden. Es findet kein externer Abruf bei Google-Servern statt. Dadurch werden keine personenbezogenen Daten an Google übermittelt.",
  "privacy.maps": "7. OpenStreetMap",
  "privacy.maps.text": "Zur Darstellung von Karten nutzen wir OpenStreetMap. Beim Aufruf einer Karte können Daten an Server von OpenStreetMap übertragen werden. Dies erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an nutzerfreundlicher Darstellung).",
  "privacy.rights": "8. Deine Rechte",
  "privacy.rights.access": "Auskunft über gespeicherte Daten",
  "privacy.rights.rectification": "Berichtigung unrichtiger Daten",
  "privacy.rights.deletion": "Löschung gespeicherter Daten",
  "privacy.rights.restriction": "Einschränkung der Verarbeitung",
  "privacy.rights.objection": "Widerspruch gegen die Verarbeitung",
  "privacy.rights.portability": "Datenübertragbarkeit",
  "privacy.rights.contact": "9. Kontaktstelle",
  "privacy.rights.contact.text": "Bei Fragen oder zur Wahrnehmung deiner Rechte kannst du dich jederzeit per E-Mail an uns wenden: info@residare.de",
  "privacy.changes": "10. Änderungen",
  "privacy.changes.text": "Wir behalten uns vor, diese Datenschutzerklärung bei Bedarf anzupassen. Gültig ist immer die aktuelle Version auf dieser Website.",
  "privacy.consent": "11. Cookie-Einwilligung",
  "privacy.consent.text": "Beim ersten Besuch unserer Website wird ggf. ein Cookie-Banner angezeigt, über das du bestimmten Verarbeitungen zustimmen oder diese ablehnen kannst. Deine Einstellungen kannst du jederzeit ändern.",
  "privacy.analytics": "12. Webanalyse und Tracking",
  "privacy.analytics.text": "Zur Optimierung unseres Angebots behalten wir uns vor, künftig Webanalyse-Dienste wie Google Analytics oder Matomo einzusetzen. Dabei können Cookies verwendet und pseudonyme Nutzungsprofile erstellt werden. Du kannst dem jederzeit widersprechen.",
  "privacy.marketing": "13. Marketing-Dienste Dritter",
  "privacy.marketing.text": "Sofern du einwilligst, können in Zukunft Dienste wie Facebook Pixel, Google Ads oder vergleichbare Technologien eingesetzt werden, um dir personalisierte Werbung anzuzeigen. Du wirst im Rahmen des Cookie-Banners transparent informiert und kannst jederzeit widerrufen."
},
  pl: {
  "nav.home": "Start",
  "nav.listings": "Oferty",
  "nav.faq": "FAQ",
  "nav.contact": "Kontakt",
  "nav.impress": "Nota prawna",
  "nav.agb": "OWH",
  "nav.privacy": "Ochrona danych",
  "agb.title": "Ogólne Warunki Handlowe (OWH)",
  "agb.scope": "1. Zakres obowiązywania",
  "agb.scope.text": "Niniejsze OWH obowiązują wszystkich użytkowników platformy internetowej Residare (zwanej dalej „Residare”), prowadzonej przez przedsiębiorcę indywidualnego Paul Smith. Regulują one relacje między operatorem a odwiedzającymi oraz zarejestrowanymi użytkownikami platformy.",
  "agb.services": "2. Usługi",
  "agb.services.text": "Residare oferuje możliwość przeglądania ogłoszeń nieruchomości oraz publikowania własnych ofert. Operator nie działa jako pośrednik i nie zawiera umów. Wszystkie usługi świadczone są zgodnie z przepisami prawa, bez licencji pośrednika.",
  "agb.costs": "3. Usługi płatne",
  "agb.costs.text": "Residare zastrzega sobie prawo do wprowadzenia opłat za niektóre funkcje – takie jak dodawanie lub wyróżnianie ogłoszeń. Użytkownicy zostaną o tym wcześniej wyraźnie poinformowani.",
  "agb.withdrawal": "4. Prawo do odstąpienia od umowy",
  "agb.withdrawal.text": "Konsumenci mają prawo odstąpić od umowy w ciągu 14 dni bez podania przyczyny. Szczegóły i formularz odstąpienia znajdują się w sekcji „Informacja o odstąpieniu”.",
  "agb.liability": "5. Odpowiedzialność",
  "agb.liability.text": "Residare nie gwarantuje poprawności, kompletności ani aktualności publikowanych treści. Za linki zewnętrzne odpowiada wyłącznie dany operator.",
  "agb.law": "6. Obowiązujące prawo",
  "agb.law.text": "Obowiązuje wyłącznie prawo niemieckie. Miejscem jurysdykcji jest siedziba operatora.",
  "agb.language": "7. Język",
  "agb.language.text": "OWH dostępne są w języku niemieckim i polskim. W przypadku wątpliwości obowiązuje wyłącznie wersja niemiecka."
}
};