
let currentLanguage = localStorage.getItem("lang") || "de";

function updateLanguage() {
  const lang = currentLanguage;
  const dict = translations[lang] || {};

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    const value = dict[key];
    if (value) el.innerText = value;
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    const value = dict[key];
    if (value) el.setAttribute("placeholder", value);
  });

  document.querySelectorAll("[data-i18n-title]").forEach(el => {
    const key = el.getAttribute("data-i18n-title");
    const value = dict[key];
    if (value) el.setAttribute("title", value);
  });

  document.querySelectorAll("[data-i18n-alt]").forEach(el => {
    const key = el.getAttribute("data-i18n-alt");
    const value = dict[key];
    if (value) el.setAttribute("alt", value);
  });
}

document.addEventListener("DOMContentLoaded", () => {
  const select = document.getElementById("language-select");
  if (select) {
    select.value = currentLanguage;
    select.addEventListener("change", e => {
      currentLanguage = e.target.value;
      localStorage.setItem("lang", currentLanguage);
      updateLanguage();
    });
  }
  updateLanguage();
});

const translations = {
  de: {},
  pl: {
  "hero.title": "Znajdź swoją nieruchomość w Polsce",
  "hero.subtitle": "Ponad granicami. Prosto. Residare.",
  "regions.title": "Najpopularniejsze regiony",
  "why.title": "Dlaczego Residare?",
  "why.one": "Transgraniczne podejście",
  "why.two": "Łatwe tłumaczenie wspomagane AI",
  "why.three": "Niezależność i elastyczność",
  "cta.title": "Skontaktuj się z nami bez zobowiązań",
  "cta.button": "Otwórz formularz kontaktowy",
  "nav.home": "Start",
  "nav.listings": "Oferty",
  "nav.faq": "FAQ",
  "nav.contact": "Kontakt",
  "nav.impress": "Nota prawna",
  "region.gdansk": "Gdańsk",
  "region.swinemuende": "Świnoujście",
  "region.misdroy": "Międzyzdroje",
  "faq.title": "Najczęstsze pytania",
  "faq.q1": "Jak działa Residare?",
  "faq.a1": "Residare łączy niemieckich i polskich zainteresowanych nieruchomościami i ułatwia oferty transgraniczne.",
  "faq.q2": "Czy jako pośrednik mogę dodawać oferty?",
  "faq.a2": "Tak, po zalogowaniu pośrednicy mogą dodawać własne ogłoszenia w panelu administracyjnym.",
  "faq.q3": "Czy korzystanie z Residare jest bezpłatne?",
  "faq.a3": "Dla zainteresowanych Residare jest bezpłatne. Pośrednicy mogą płacić za funkcje premium.",
  "impressum.title": "Impressum",
  "impressum.owner": "Dane zgodnie z §5 TMG:\\nResidare GmbH\\nul. Przykładowa 1\\n12345 Berlin",
  "impressum.represented": "Reprezentowana przez:\\nMax Mustermann",
  "impressum.contact": "Kontakt:\\nE-mail: kontakt@residare.de\\nTelefon: +49 123 456789",
  "impressum.legal": "Odpowiedzialny za treść zgodnie z §55 ust. 2 RStV:\\nMax Mustermann, jak powyżej",
  "contact.title": "Formularz kontaktowy",
  "contact.name": "Twoje imię",
  "contact.email": "Twój e-mail",
  "contact.message": "Wiadomość",
  "contact.send": "Wyślij",
  "admin.title": "Dodaj nowe ogłoszenie",
  "admin.title.label": "Tytuł",
  "admin.location": "Lokalizacja",
  "admin.size": "Powierzchnia (m²)",
  "admin.price": "Cena (€)",
  "admin.image": "Dodaj zdjęcie",
  "admin.language": "Język ogłoszenia",
  "admin.description": "Opis",
  "admin.submit": "Zapisz ogłoszenie",
  "admin.transaction": "Typ ogłoszenia",
  "admin.sell": "Sprzedaż",
  "admin.rent": "Wynajem",
  "type.flat": "Mieszkanie",
  "type.house": "Dom",
  "type.plot": "Działka",
  "type.lokal": "Lokal",
  "type.building": "Budynek użytkowy",
  "type.room": "Pokój",
  "form.button_0": "☰",
  "nav.favorites": "Ulubione",
  "nav.post": "Dodaj ogłoszenie",
  "nav.blog": "Blog",
  "nav.login": "Zaloguj się",
  "form.select_0.0": "🇩🇪",
  "form.select_0.1": "🇵🇱",
  "form.section_0": "Grunddaten",
  "form.label_0": "Powierzchnia mieszkalna",
  "form.label_1": "Powierzchnia użytkowa",
  "form.label_2": "Preis",
  "form.select_1.0": "EUR",
  "form.select_1.1": "PLN",
  "form.label_3": "Preis pro m²",
  "form.select_2.0": "EUR",
  "form.select_2.1": "PLN",
  "form.label_4": "Anzahl Zimmer",
  "form.label_5": "Stockwerk",
  "form.label_6": "Anzahl Stockwerke",
  "form.label_7": "Aufzug",
  "form.button_1": "Ja",
  "form.button_2": "Nein",
  "form.label_8": "Gebäudetyp",
  "form.select_3.0": "Wohnblock",
  "form.select_3.1": "Mehrfamilienhaus",
  "form.select_3.2": "Freistehendes Haus",
  "form.select_3.3": "Altbau",
  "form.select_3.4": "Apartmenthaus",
  "form.select_3.5": "Loft",
  "form.select_3.6": "Residenz",
  "form.label_9": "Rok budowy",
  "form.label_10": "Zustand",
  "form.select_4.0": "Hochwertig",
  "form.select_4.1": "Sehr gut",
  "form.select_4.2": "Gut",
  "form.select_4.3": "Auffrischungsbedürftig",
  "form.select_4.4": "Renovierungsbedürftig",
  "form.select_4.5": "Neubau (unfertig)",
  "form.select_4.6": "Neu & bezugsfertig",
  "form.label_11": "Energieausweis",
  "form.button_3": "Ja",
  "form.button_4": "Nein",
  "form.section_1": "Weitere Angaben",
  "form.label_12": "Ort",
  "form.label_13": "Opis",
  "form.label_14": "Verfügbarkeit",
  "form.select_5.0": "Sofort",
  "form.select_5.1": "Nach Vereinbarung",
  "form.select_5.2": "Genaues Datum",
  "form.label_15": "Eigentumsform",
  "form.select_6.0": "Eigentum",
  "form.select_6.1": "Genossenschaft",
  "form.select_6.2": "Andere",
  "form.label_16": "Grundbuch vorhanden",
  "form.button_5": "Ja",
  "form.button_6": "Nein",
  "form.label_17": "Hausgeld",
  "form.select_7.0": "EUR",
  "form.select_7.1": "PLN",
  "form.label_18": "Nadaje się na biuro",
  "form.label_19": "Możliwa zamiana",
  "form.label_20": "Balkon",
  "form.button_7": "Ja",
  "form.button_8": "Nein",
  "form.label_21": "Keller",
  "form.button_9": "Ja",
  "form.button_10": "Nein",
  "form.label_22": "Garten",
  "form.button_11": "Ja",
  "form.button_12": "Nein",
  "form.label_23": "Dachboden",
  "form.button_13": "Ja",
  "form.button_14": "Nein",
  "form.label_24": "Stellplatz",
  "form.button_15": "Ja",
  "form.button_16": "Nein",
  "form.label_25": "Einbauküche",
  "form.button_17": "Ja",
  "form.button_18": "Nein",
  "form.label_26": "Möbliert",
  "form.button_19": "Ja",
  "form.button_20": "Nein",
  "form.button_21": "Teilweise",
  "form.label_27": "Haushaltsgeräte",
  "form.button_22": "Ja",
  "form.button_23": "Nein",
  "form.button_24": "Teilweise",
  "form.label_28": "Anzahl der Etagen",
  "form.select_8.0": "1",
  "form.select_8.1": "2",
  "form.label_29": "Anzahl Badezimmer",
  "form.select_9.0": "1",
  "form.select_9.1": "2",
  "form.label_30": "Badezimmerausstattung",
  "form.select_10.0": "Badewanne",
  "form.select_10.1": "Dusche",
  "form.select_10.2": "Bidet",
  "form.select_10.3": "Mit Fenster",
  "form.label_31": "Technik der Bauweise",
  "form.select_11.0": "Neue Technologie",
  "form.select_11.1": "Traditionell / Ziegel",
  "form.select_11.2": "Großplatte",
  "form.label_32": "Stan instalacji",
  "form.select_12.0": "Neu / Erneuert",
  "form.select_12.1": "Guter Zustand",
  "form.select_12.2": "Teilweise erneuert",
  "form.select_12.3": "Erneuerungsbedürftig",
  "form.select_12.4": "Nicht verlegt",
  "form.label_33": "Fenster",
  "form.select_13.0": "Neu / Erneuert",
  "form.select_13.1": "Teilweise erneuert",
  "form.select_13.2": "Erneuerungsbedürftig",
  "form.select_13.3": "Historisch",
  "form.select_13.4": "Kunststoff",
  "form.select_13.5": "Holz",
  "form.select_13.6": "Aluminium",
  "form.label_34": "Rodzaj ogrzewania",
  "form.select_14.0": "Fernwärme",
  "form.select_14.1": "Eigenständig",
  "form.select_14.2": "Zentralheizung",
  "form.select_14.3": "Keine Heizung",
  "form.select_14.4": "Ofen",
  "form.select_14.5": "Kamin",
  "form.select_14.6": "Elektro",
  "form.select_14.7": "Gas",
  "form.select_14.8": "Öl",
  "form.select_14.9": "Andere",
  "form.label_35": "Wasserzähler",
  "form.button_25": "Ja",
  "form.button_26": "Nein",
  "form.label_36": "Klimaanlage",
  "form.button_27": "Ja",
  "form.button_28": "Nein",
  "form.label_37": "Internet",
  "form.button_29": "Ja",
  "form.button_30": "Nein",
  "form.label_38": "Kabel-TV",
  "form.button_31": "Ja",
  "form.button_32": "Nein",
  "form.label_39": "Telefon",
  "form.button_33": "Ja",
  "form.button_34": "Nein",
  "form.label_40": "Środki bezpieczeństwa",
  "form.label_41": "Sicherheitstür",
  "form.label_42": "Sicherheitsrollos",
  "form.label_43": "Gegensprechanlage / Videofon",
  "form.label_44": "Alarmanlage",
  "form.label_45": "Kameraüberwachung",
  "form.label_46": "Sicherheitsdienst",
  "form.label_47": "Eingezäuntes Gelände",
  "form.label_48": "Behindertengerecht",
  "form.button_35": "Ja",
  "form.button_36": "Nein",
  "form.label_49": "Umgebungsbebauung",
  "form.select_15.0": "Wohnblocksiedlung",
  "form.select_15.1": "Einfamilienhaussiedlung",
  "form.select_15.2": "Lockere Einfamilienhausbebauung",
  "form.select_15.3": "Grünflächen / Freizeitflächen",
  "form.select_15.4": "Gewerbeobjekte",
  "form.select_15.5": "Industrieobjekte",
  "form.select_15.6": "Unbebautes Gelände",
  "form.label_50": "Lautstärke",
  "form.select_16.0": "Ruhig",
  "form.select_16.1": "Mittelruhig",
  "form.select_16.2": "Mittel laut",
  "form.select_16.3": "Laut",
  "form.label_51": "Natur in der Umgebung",
  "form.select_17.0": "Wiese",
  "form.select_17.1": "Wald",
  "form.select_17.2": "See",
  "form.select_17.3": "Fluss",
  "form.select_17.4": "Meer",
  "form.select_17.5": "Berge",
  "form.section_2": "Fotos hinzufügen",
  "form.button_37": "Zapisz ogłoszenie",
  "form.button_38": "Später abschließen",
  "nav.agb": "Regulamin",
  "nav.privacy": "Polityka prywatności",
  "auto._2025_residare": "© 2025 Residare",
  "form.placeholder_z. b._danzig": "z. B. Danzig",
  "form.placeholder_beschreibung_der_imm": "Beschreibung der Immobilie",
  "auto.": "auto.",
  "hero.dream": "hero.dream",
  "listing.subtitle1": "listing.subtitle1",
  "listing.subtitle2": "listing.subtitle2",
  "listing.subtitle3": "listing.subtitle3",
  "listing.title1": "listing.title1",
  "listing.title2": "listing.title2",
  "listing.title3": "listing.title3",
  "login.create": "login.create",
  "login.submit": "login.submit",
  "login.title": "login.title",
  "placeholder.form.placeholder_beschreibung_der_imm": "placeholder.form.placeholder_beschreibung_der_imm",
  "placeholder.form.placeholder_z. b._danzig": "placeholder.form.placeholder_z. b._danzig",
  "placeholder.search.area": "placeholder.search.area",
  "placeholder.search.location": "placeholder.search.location",
  "placeholder.search.price": "placeholder.search.price",
  "placeholder.search.rooms": "placeholder.search.rooms",
  "privacy.accessData": "privacy.accessData",
  "privacy.accessData.text": "privacy.accessData.text",
  "privacy.analytics": "privacy.analytics",
  "privacy.analytics.text": "privacy.analytics.text",
  "privacy.changes": "privacy.changes",
  "privacy.changes.text": "privacy.changes.text",
  "privacy.consent": "privacy.consent",
  "privacy.consent.text": "privacy.consent.text",
  "privacy.contactform": "privacy.contactform",
  "privacy.contactform.text": "privacy.contactform.text",
  "privacy.controller": "privacy.controller",
  "privacy.controller.text": "privacy.controller.text",
  "privacy.cookies": "privacy.cookies",
  "privacy.cookies.text": "privacy.cookies.text",
  "privacy.googlefonts": "privacy.googlefonts",
  "privacy.googlefonts.text": "privacy.googlefonts.text",
  "privacy.hosting": "privacy.hosting",
  "privacy.hosting.text": "privacy.hosting.text",
  "privacy.maps": "privacy.maps",
  "privacy.maps.text": "privacy.maps.text",
  "privacy.marketing": "privacy.marketing",
  "privacy.marketing.text": "privacy.marketing.text",
  "privacy.rights": "privacy.rights",
  "privacy.rights.access": "privacy.rights.access",
  "privacy.rights.contact": "privacy.rights.contact",
  "privacy.rights.contact.text": "privacy.rights.contact.text",
  "privacy.rights.deletion": "privacy.rights.deletion",
  "privacy.rights.objection": "privacy.rights.objection",
  "privacy.rights.portability": "privacy.rights.portability",
  "privacy.rights.rectification": "privacy.rights.rectification",
  "privacy.rights.restriction": "privacy.rights.restriction",
  "privacy.title": "privacy.title",
  "property.building": "Budynek użytkowy",
  "property.flat": "Mieszkanie",
  "property.house": "Dom",
  "property.lokal": "Lokal użytkowy",
  "search.button": "Szukaj",
  "search.placeholder": "Miasto / dzielnica / ulica",
  "search.save": "search.save",
  "transaction.buy": "Kupno",
  "transaction.rent": "Wynajem",
  "thank.title": "",
  "thank.message": ""
}
};
